packages:
  - 'apps/*'

catalog:
  "@biomejs/biome": ^2.2.4
  "@cloudflare/workers-types": ^4.20230605.0
  "@hono/vite-build": ^1.6.0
  "@hono/vite-dev-server": ^0.23.0
  "@mdx-js/rollup": ^3.1.0
  "@mermaid-js/mermaid-cli": ^11.4.2
  "@resvg/resvg-js": ^2.6.2
  "@resvg/resvg-wasm": ^2.6.2
  "@swc-node/register": ^1.10.10
  "@swc/cli": ^0.7.3
  "@swc/core": ^1.11.24
  "@taga3s/rss-generator": "npm:@jsr/taga3s__rss-generator@^0.1.8"
  "@types/hast": ^3.0.4
  "@types/mdast": ^4.0.4
  "@types/node": ^24.5.2
  "@types/unist": ^3.0.3
  "hast-util-to-html": ^9.0.5
  "hono": ^4.6.20
  "honox": ^0.1.33
  "puppeteer": ^24.8.0
  "rehype-parse": ^9.0.1
  "rehype-stringify": ^10.0.1
  "remark-breaks": ^4.0.0
  "remark-extract-frontmatter": ^3.2.0
  "remark-frontmatter": ^5.0.0
  "remark-gfm": ^4.0.1
  "remark-mdx-frontmatter": ^5.1.0
  "remark-parse": ^11.0.0
  "remark-rehype": ^11.1.2
  "remark-stringify": ^11.0.0
  "shiki": ^3.3.0
  "turbo": ^2.5.8
  "to-vfile": ^8.0.0
  "unified": ^11.0.5
  "unist-util-visit": ^5.0.0
  "vite": ^7.0.0
  "vitest": ^3.1.2
  "satori": ^0.18.0
  "sharp": ^0.34.1
  "wrangler": ^4.40.0
  "yoga-wasm-web": ^0.3.3
  "yaml": ^2.8.1

minimumReleaseAge: 1
