name: Comment Preview URL
description: comment preview url action

inputs:
  name:
    required: true
    description: name
  target_url:
    required: true
    description: target_url
  pr_number:
    required: true
    description: pr_number

runs:
  using: composite
  steps:
    - name: Create comment
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        echo "#### ${{ inputs.name }} Preview URL:
        ${{ inputs.target_url }}
        " > .tmp.txt
        gh pr comment ${{ inputs.pr_number }} --body-file .tmp.txt || gh pr comment ${{ inputs.pr_number }} --body-file .tmp.txt
      shell: bash
