name: Setup CI
description: Setup CI environment

inputs:
  node-version:
    required: false
    description: "Specify Node.js version. If this is not specified, Node.js version specified in .node-version will be used"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        package_json_file: "package.json"
        run_install: false

    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: .node-version
        cache: "pnpm"

    - run: pnpm install
      shell: bash
