name: Setup CI
description: Setup CI environment

inputs:
  node-version:
    required: false
    description: "Specify Node.js version. If this is not specified, Node.js version specified in .node-version will be used"

runs:
  using: "composite"
  steps:
    - uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa # v1
      with:
        node-version-file: .node-version
        cache: true

    - run: vp install
      shell: bash
