name: Setup CI
description: Setup CI environment

inputs:
  node-version:
    required: false
    description: "Specify Node.js version. If this is not specified, Node.js version specified in .node-version will be used"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        package_json_file: "package.json"
        run_install: false

    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: .node-version
        cache: "pnpm"

    - run: pnpm install
      shell: bash
