name: Setup CI
description: Setup CI environment

inputs:
  node-version:
    required: false
    description: "Specify Node.js version. If this is not specified, Node.js version specified in .node-version will be used"

runs:
  using: "composite"
  steps:
    - uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1
      with:
        node-version-file: .node-version
        cache: true

    - run: vp install
      shell: bash
