name: Setup CI
description: Setup CI environment

inputs:
  node-version:
    required: false
    description: "Specify Node.js version. If this is not specified, Node.js version specified in .node-version will be used"

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      with:
        package_json_file: "package.json"
        run_install: false

    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: .node-version
        cache: "pnpm"

    - run: pnpm install
      shell: bash

    - run: pnpm --filter "@taga3s/website" install-puppeteer
      shell: bash
