name: Comment Preview URL

on:
  workflow_call:
    inputs:
      name:
        description: 'Project name'
        required: true
        type: string
      target_url:
        description: 'Preview deployment URL'
        required: true
        type: string
      pr_number:
        description: 'Pull request number'
        required: true
        type: number

permissions:
  pull-requests: write

jobs:
  comment-preview-url:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Comment Preview URL
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "#### ${{ inputs.name }} Preview URL:
          ${{ inputs.target_url }}
          " > .tmp.txt
          gh pr comment ${{ inputs.pr_number }} --body-file .tmp.txt
