name: deploy

on:
  push:
    branches:
      - main
    paths:
      - "packages/website/**"
      - "packages/mdx2json/**"
      - "packages/dispatcher/**"
      - "packages/blog-engine/**"
      - "packages/metrics-engine/**"
      - "assets/blog/**"
      - ".github/workflows/deploy.yaml"

jobs:
  paths-changes:
    runs-on: ubuntu-slim
    outputs:
      website-changed: ${{ steps.paths-changes.outputs.website }}
      dispatcher-changed: ${{ steps.paths-changes.outputs.dispatcher }}
      blog-engine-changed: ${{ steps.paths-changes.outputs.blog-engine }}
      metrics-engine-changed: ${{ steps.paths-changes.outputs.metrics-engine }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: paths-changes
        with:
          filters: |
            workflows: &workflows
              - '.github/workflows/deploy.yaml'
            website:
              - *workflows
              - 'assets/blog/**'
              - 'packages/mdx2json/**'
              - 'packages/website/**'
            dispatcher:
              - *workflows
              - 'packages/dispatcher/**'
            blog-engine:
              - *workflows
              - 'packages/blog-engine/**'
            metrics-engine:
              - *workflows
              - 'packages/metrics-engine/**'

  run-mdx2json:
    needs: [paths-changes]
    if: needs.paths-changes.outputs.website-changed == 'true'
    uses: $/.github/workflows/reusable-mdx2json.yaml
    secrets: inherit

  deploy-website:
    needs: [paths-changes]
    runs-on: ubuntu-latest
    if: needs.paths-changes.outputs.website-changed == 'true'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: $/.github/actions/setup-ci
        with:
          install-packages: "@taga3s-dev/website"

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy ./dist/index.mjs --no-bundle --config wrangler.jsonc
          workingDirectory: ./packages/website
        env:
          POLICY_AUD: ${{ secrets.CLOUDFLARE_ACCESS_AUD }}
          TEAM_DOMAIN: ${{ secrets.CLOUDFLARE_ACCESS_TEAM_DOMAIN }}

  deploy-dispatcher:
    needs: [paths-changes]
    runs-on: ubuntu-latest
    if: needs.paths-changes.outputs.dispatcher-changed == 'true'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: $/.github/actions/setup-ci
        with:
          install-packages: "@taga3s-dev/dispatcher"

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --minify --config wrangler.jsonc
          workingDirectory: ./packages/dispatcher

  deploy-blog-engine:
    needs: [paths-changes]
    runs-on: ubuntu-latest
    if: needs.paths-changes.outputs.blog-engine-changed == 'true'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: $/.github/actions/setup-ci
        with:
          install-packages: "@taga3s-dev/blog-engine"

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --minify --config wrangler.jsonc
          workingDirectory: ./packages/blog-engine

  deploy-metrics-engine:
    needs: [paths-changes]
    runs-on: ubuntu-latest
    if: needs.paths-changes.outputs.metrics-engine-changed == 'true'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: $/.github/actions/setup-ci
        with:
          install-packages: "@taga3s-dev/metrics-engine"

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --minify --config wrangler.jsonc
          workingDirectory: ./packages/metrics-engine
