name: deploy

on:
  push:
    paths:
      - "packages/dispatcher/**"
      - ".github/workflows/deploy-dispather-temporal.yaml"

jobs:
  deploy-dispatcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: $/.github/actions/setup-ci
        with:
          install-packages: "@taga3s-dev/dispatcher"

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --minify --config wrangler.jsonc
          workingDirectory: ./packages/dispatcher

  deploy-blog-engine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: $/.github/actions/setup-ci
        with:
          install-packages: "@taga3s-dev/blog-engine"

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --minify --config wrangler.jsonc
          workingDirectory: ./packages/blog-engine
