name: deploy-preview

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/website/**"
      - "packages/mdx2json/**"
      - "assets/blog/**"
      - ".github/workflows/deploy-preview.yaml"
    types: [opened, synchronize, reopened, closed]

jobs:
  paths-changes:
    runs-on: ubuntu-slim
    outputs:
      website-changed: ${{ steps.paths-changes.outputs.website }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        id: paths-changes
        with:
          filters: |
            workflows: &workflows
              - '.github/workflows/deploy-preview.yaml'
            website:
              - *workflows
              - 'assets/blog/**'
              - 'packages/mdx2json/**'
              - 'packages/website/**'

  run-mdx2json:
    needs: [paths-changes]
    if: needs.paths-changes.outputs.website-changed == 'true' && github.event.action != 'closed'
    uses: $/.github/workflows/reusable-mdx2json.yaml
    with:
      is_preview: true
    secrets: inherit

  deploy-preview-website:
    needs: [paths-changes]
    runs-on: ubuntu-latest
    if: needs.paths-changes.outputs.website-changed == 'true' && github.event.action != 'closed'
    outputs:
      preview-url: ${{ steps.preview.outputs.preview-url }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: $/.github/actions/setup-ci
        with:
          install-packages: "@taga3s-dev/website"

      - name: Deploy preview
        id: preview
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.136.3"
          command: preview --config wrangler.jsonc
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./packages/website

  cleanup:
    needs: [paths-changes]
    runs-on: ubuntu-latest
    if: needs.paths-changes.outputs.website-changed == 'true' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: $/.github/actions/setup-ci
        with:
          install-packages: "@taga3s-dev/website"

      - name: Deploy preview
        id: preview
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: "4.136.3"
          command: preview --config wrangler.jsonc
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./packages/website
