name: Renovate Config Validator

on:
  workflow_dispatch:
  push:
    paths:
      - "renovate.json"
      - ".github/workflows/renovate-config-validator.yaml"

jobs:
  renovate-config-validator:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: validate renovate.json
        run: npx --package=renovate -c renovate-config-validator
