name: Versions upload

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  deployments: write
  statuses: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Disable AppArmor
        # Ubuntu >= 23 has AppArmor enabled by default, which breaks Puppeteer.
        # See https://github.com/puppeteer/puppeteer/issues/12818 "No usable sandbox!"
        # this is taken from the solution used in Puppeteer's own CI: https://github.com/puppeteer/puppeteer/pull/13196
        # The alternative is to pin Ubuntu 22 or to use aa-exec to disable AppArmor for commands that need Puppeteer.
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
        shell: bash

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: 'package.json'
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      - name: Install Puppeteer
        run: pnpm install-puppeteer
      
      - name: Generate RSS feed
        run: pnpm generate:rss

      - name: Build
        run: pnpm build

      - name: Upload to Cloudflare Workers
        id: cloudflare-workers-upload
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: versions upload --config wrangler.jsonc
      
      - name: Comment Preview URL
        uses: ./.github/actions/comment-preview-url
        with:
          target_url: ${{ steps.cloudflare-workers-upload.outputs.deployment-url }}
          pr_number: ${{ github.event.number }}
        if: github.event_name == 'pull_request'
