name: website-versions-upload

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/website/**'
      - '.github/workflows/website-versions-upload.yaml'

permissions:
  pull-requests: write

jobs:
  upload-website:
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.upload.outputs.deployment-url }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-ci

      - name: Generate Atom feed
        run: vp run --filter "@taga3s-dev/website" generate:atom

      - name: Build
        run: vp run build:website

      - name: Upload to Cloudflare Workers
        id: upload
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: versions upload --config wrangler.jsonc
          workingDirectory: ./apps/website

  comment-preview-url:
    needs: upload-website
    uses: ./.github/workflows/comment-preview-url.yaml
    with:
      name: "@taga3s-dev/website"
      target_url: ${{ needs.upload-website.outputs.deployment-url }}
      pr_number: ${{ github.event.number }}
