name: website-versions-upload

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/website/**'
      - '.github/workflows/website-versions-upload.yaml'

permissions:
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Disable AppArmor
        # Ubuntu >= 23 has AppArmor enabled by default, which breaks Puppeteer.
        # See https://github.com/puppeteer/puppeteer/issues/12818 "No usable sandbox!"
        # this is taken from the solution used in Puppeteer's own CI: https://github.com/puppeteer/puppeteer/pull/13196
        # The alternative is to pin Ubuntu 22 or to use aa-exec to disable AppArmor for commands that need Puppeteer.
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
        shell: bash

      - uses: ./.github/actions/setup-ci

      - run: pnpm --filter "@taga3s/website" install-puppeteer
        shell: bash

      - name: Generate RSS feed
        run: pnpm --filter "@taga3s/website" generate:rss

      - name: Build
        run: pnpm build:website

      - name: Upload to Cloudflare Workers
        id: upload
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: versions upload --config wrangler.jsonc
          workingDirectory: ./apps/website

      - name: Comment Preview URL
        uses: ./.github/actions/comment-preview-url
        with:
          name: "@taga3s/website"
          target_url: ${{ steps.upload.outputs.deployment-url }}
          pr_number: ${{ github.event.number }}
