name: website-deploy

on:
  push:
    branches:
      - main
    paths:
      - 'apps/website/**'
      - '.github/workflows/website-deploy.yaml'

env:
  VITE_WORKERS_ENV: "prod"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/setup-ci

      - name: Generate Atom feed
        run: vp run --filter "@taga3s-dev/website" generate:atom

      - name: Build
        run: vp run build:website

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3.15.0
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --minify --config wrangler.jsonc
          workingDirectory: ./apps/website
        env:
          POLICY_AUD: ${{ secrets.CLOUDFLARE_ACCESS_AUD }}
          TEAM_DOMAIN: ${{ secrets.CLOUDFLARE_ACCESS_TEAM_DOMAIN }}
